on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Send GitHub Action trigger data to Slack workflow
        if: ${{ always() }}
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {"text":"A GitHub Action has ${{job.status}}","attachments":[{"color": "${{ (job.status == 'success' && 'good') || (job.status == 'failure' && 'danger') || 'warning' }}", "fields":[{"title":"Repository","short":false,"value":"<${{ github.event.repository.url }}|${{ github.event.repository.url }}>"},{"title":"Ref","short":false,"value":"${{ github.ref }}"},{"title":"Commit","short":false,"value":"<${{ github.event.head_commit.url }}|${{ github.sha }}>"},{"title":"Author","short":false,"value":"${{ github.event.head_commit.author.name }}"},{"title":"Message","short":false,"value":"${{ github.event.head_commit.message }}"},{"title":"Workflow","short":false,"value":"<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"}]}]}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
