on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {"text":"A GitHub Action has succeeded","attachments":[{"color":"good","fields":[{"title":"Repository","short":false,"value":"<${{ github.event.repository.url }}|${{ github.event.repository.url }}>"},{"title":"Ref","short":false,"value":"${{ github.context.ref }}"},{"title":"Commit","short":false,"value":"<${{ github.event.head_commit.url }}|${{ github.sha }}>"},{"title":"Author","short":false,"value":"${{ github.event.head_commit.author.name }}"},{"title":"Message","short":false,"value":"${{ github.event.head_commit.message }}"},{"title":"Workflow","short":false,"value":"<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"}]}]}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
